version: "3"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    command: >
            sh -c "cd /app/backend &&
            python manage.py wait_for_db &&
            python3 manage.py makemigrations && 
            python3 manage.py migrate && 
            python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/backend/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - main
    env_file:
      - ./.env/dev.env

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/posgresql/data
    networks:
      - main

  app:
    restart: always
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/my-app/src
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    networks:
      - main

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - app
    networks:
      - main
 
networks:
  main:

volumes:
  pgdata:
  static_volume:
