# Generated by Django 3.2.25 on 2024-06-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=5000)),
                ('user', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Django App Model',
                'verbose_name_plural': 'Django App Model',
                'db_table': 'django_app_model',
            },
        ),
    ]
